{"$message_type":"diagnostic","message":"cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`","code":{"code":"E0425","explanation":"An unresolved name was used.\n\nErroneous code examples:\n\n```compile_fail,E0425\nsomething_that_doesnt_exist::foo;\n// error: unresolved name `something_that_doesnt_exist::foo`\n\n// or:\n\ntrait Foo {\n    fn bar() {\n        Self; // error: unresolved name `Self`\n    }\n}\n\n// or:\n\nlet x = unknown_variable;  // error: unresolved name `unknown_variable`\n```\n\nPlease verify that the name wasn't misspelled and ensure that the\nidentifier being referred to is valid for the given situation. Example:\n\n```\nenum something_that_does_exist {\n    Foo,\n}\n```\n\nOr:\n\n```\nmod something_that_does_exist {\n    pub static foo : i32 = 0i32;\n}\n\nsomething_that_does_exist::foo; // ok!\n```\n\nOr:\n\n```\nlet unknown_variable = 12u32;\nlet x = unknown_variable; // ok!\n```\n\nIf the item is not defined in the current module, it must be imported using a\n`use` statement, like so:\n\n```\n# mod foo { pub fn bar() {} }\n# fn main() {\nuse foo::bar;\nbar();\n# }\n```\n\nIf the item you are importing is not defined in some super-module of the\ncurrent module, then it must also be declared as public (e.g., `pub fn`).\n"},"level":"error","spans":[{"file_name":"/data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/ffi/cpython/unicodeobject.rs","byte_start":6030,"byte_end":6091,"line_start":224,"line_end":224,"column_start":1,"column_end":62,"is_primary":false,"text":[{"text":"pub unsafe fn PyUnicode_IS_READY(op: *mut PyObject) -> c_uint {","highlight_start":1,"highlight_end":62}],"label":"similarly named function `PyUnicode_IS_READY` defined here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/types/string.rs","byte_start":8891,"byte_end":8906,"line_start":232,"line_end":232,"column_start":30,"column_end":45,"is_primary":true,"text":[{"text":"            let ready = ffi::PyUnicode_READY(ptr);","highlight_start":30,"highlight_end":45}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"a function with a similar name exists","code":null,"level":"help","spans":[{"file_name":"/data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/types/string.rs","byte_start":8891,"byte_end":8906,"line_start":232,"line_end":232,"column_start":30,"column_end":45,"is_primary":true,"text":[{"text":"            let ready = ffi::PyUnicode_READY(ptr);","highlight_start":30,"highlight_end":45}],"label":null,"suggested_replacement":"PyUnicode_IS_READY","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror[E0425]\u001b[0m\u001b[0m\u001b[1m: cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m--> \u001b[0m\u001b[0m/data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/types/string.rs:232:30\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;12m232\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m \u001b[0m\u001b[0m            let ready = ffi::PyUnicode_READY(ptr);\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m                              \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^^^^^^^^^^^\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9mhelp: a function with a similar name exists: `PyUnicode_IS_READY`\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m::: \u001b[0m\u001b[0m/data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/ffi/cpython/unicodeobject.rs:224:1\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;12m224\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m \u001b[0m\u001b[0mpub unsafe fn PyUnicode_IS_READY(op: *mut PyObject) -> c_uin\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m...\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m-------------------------------------------------------------\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12msimilarly named function `PyUnicode_IS_READY` defined here\u001b[0m\n\n"}
{"$message_type":"diagnostic","message":"aborting due to 1 previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m: aborting due to 1 previous error\u001b[0m\n\n"}
{"$message_type":"diagnostic","message":"For more information about this error, try `rustc --explain E0425`.","code":null,"level":"failure-note","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1mFor more information about this error, try `rustc --explain E0425`.\u001b[0m\n"}
